/* --COPYRIGHT--,BSD
 * Copyright (c) 2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * --/COPYRIGHT--*/


// Generated by Captivate Design Center v1_83_00_08 on Sat Jan 28 17:53:48 KST 2023


//*****************************************************************************
// CAPT_UserConfig.c
//
// \version 1.83.00.05
// Released on May 15, 2020
//
//*****************************************************************************

//*****************************************************************************
//
// NOTE: This is an automatically generated source code file!  The Captivate
// Design Center generates the User Configuration file automatically based
// upon the sensor layout that was created.
//
// Changes to this file will be OVERWRITTEN if a you select
// "Update Existing Project" under "Generate Source Code" in the Design Center.
//
// To avoid interference with the code generation process, keep ALL application
// code external to this file.
//
//*****************************************************************************

#include "CAPT_UserConfig.h"

//*****************************************************************************
//
//! Captivate Element Definitions
//! All elements in this application are defined below.
//! Each element has 3 components:
//!  1) a raw count array (One index per freq. scanned) (uint16_t)
//!  2) a tuning array (One index per freq. scanned) (tCaptivateElementTuning)
//!  3) a element structure (tElement)
//
//*****************************************************************************
// Sensor: BTN00, Element: E00
uint16_t BTN00_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E00 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E00_RawCnts,
    .pTuning = BTN00_E00_Tuning,
};

// Sensor: BTN00, Element: E01
uint16_t BTN00_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E01 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E01_RawCnts,
    .pTuning = BTN00_E01_Tuning,
};

// Sensor: BTN00, Element: E02
uint16_t BTN00_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E02 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E02_RawCnts,
    .pTuning = BTN00_E02_Tuning,
};

// Sensor: BTN00, Element: E03
uint16_t BTN00_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E03 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E03_RawCnts,
    .pTuning = BTN00_E03_Tuning,
};

// Sensor: BTN00, Element: E04
uint16_t BTN00_E04_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E04_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E04 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E04_RawCnts,
    .pTuning = BTN00_E04_Tuning,
};

// Sensor: BTN00, Element: E05
uint16_t BTN00_E05_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E05_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E05 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E05_RawCnts,
    .pTuning = BTN00_E05_Tuning,
};

// Sensor: BTN00, Element: E06
uint16_t BTN00_E06_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E06_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E06 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E06_RawCnts,
    .pTuning = BTN00_E06_Tuning,
};

// Sensor: BTN00, Element: E07
uint16_t BTN00_E07_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E07_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E07 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E07_RawCnts,
    .pTuning = BTN00_E07_Tuning,
};

// Sensor: BTN00, Element: E08
uint16_t BTN00_E08_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E08_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E08 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E08_RawCnts,
    .pTuning = BTN00_E08_Tuning,
};

// Sensor: BTN00, Element: E09
uint16_t BTN00_E09_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E09_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E09 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E09_RawCnts,
    .pTuning = BTN00_E09_Tuning,
};

// Sensor: BTN00, Element: E10
uint16_t BTN00_E10_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E10_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E10 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E10_RawCnts,
    .pTuning = BTN00_E10_Tuning,
};

// Sensor: BTN00, Element: E11
uint16_t BTN00_E11_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E11_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E11 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E11_RawCnts,
    .pTuning = BTN00_E11_Tuning,
};

// Sensor: BTN00, Element: E12
uint16_t BTN00_E12_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E12_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E12 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E12_RawCnts,
    .pTuning = BTN00_E12_Tuning,
};

// Sensor: BTN00, Element: E13
uint16_t BTN00_E13_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E13_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E13 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E13_RawCnts,
    .pTuning = BTN00_E13_Tuning,
};

// Sensor: BTN00, Element: E14
uint16_t BTN00_E14_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E14_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E14 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E14_RawCnts,
    .pTuning = BTN00_E14_Tuning,
};

// Sensor: BTN00, Element: E15
uint16_t BTN00_E15_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN00_E15_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN00_E15 =
{
    .ui8TxPin = 3,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = BTN00_E15_RawCnts,
    .pTuning = BTN00_E15_Tuning,
};

// Sensor: SLD00, Element: E00
uint16_t SLD00_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD00_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD00_E00 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD00_E00_RawCnts,
    .pTuning = SLD00_E00_Tuning,
};

// Sensor: SLD00, Element: E01
uint16_t SLD00_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD00_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD00_E01 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD00_E01_RawCnts,
    .pTuning = SLD00_E01_Tuning,
};

// Sensor: SLD00, Element: E02
uint16_t SLD00_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD00_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD00_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD00_E02_RawCnts,
    .pTuning = SLD00_E02_Tuning,
};

// Sensor: SLD00, Element: E03
uint16_t SLD00_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD00_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD00_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD00_E03_RawCnts,
    .pTuning = SLD00_E03_Tuning,
};

// Sensor: SLD01, Element: E00
uint16_t SLD01_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD01_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD01_E00 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD01_E00_RawCnts,
    .pTuning = SLD01_E00_Tuning,
};

// Sensor: SLD01, Element: E01
uint16_t SLD01_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD01_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD01_E01 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD01_E01_RawCnts,
    .pTuning = SLD01_E01_Tuning,
};

// Sensor: SLD01, Element: E02
uint16_t SLD01_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD01_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD01_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD01_E02_RawCnts,
    .pTuning = SLD01_E02_Tuning,
};

// Sensor: SLD01, Element: E03
uint16_t SLD01_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD01_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD01_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD01_E03_RawCnts,
    .pTuning = SLD01_E03_Tuning,
};

// Sensor: SLD02, Element: E00
uint16_t SLD02_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD02_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD02_E00 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD02_E00_RawCnts,
    .pTuning = SLD02_E00_Tuning,
};

// Sensor: SLD02, Element: E01
uint16_t SLD02_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD02_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD02_E01 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD02_E01_RawCnts,
    .pTuning = SLD02_E01_Tuning,
};

// Sensor: SLD02, Element: E02
uint16_t SLD02_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD02_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD02_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD02_E02_RawCnts,
    .pTuning = SLD02_E02_Tuning,
};

// Sensor: SLD02, Element: E03
uint16_t SLD02_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD02_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD02_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD02_E03_RawCnts,
    .pTuning = SLD02_E03_Tuning,
};

// Sensor: SLD03, Element: E00
uint16_t SLD03_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD03_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD03_E00 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD03_E00_RawCnts,
    .pTuning = SLD03_E00_Tuning,
};

// Sensor: SLD03, Element: E01
uint16_t SLD03_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD03_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD03_E01 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD03_E01_RawCnts,
    .pTuning = SLD03_E01_Tuning,
};

// Sensor: SLD03, Element: E02
uint16_t SLD03_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD03_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD03_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD03_E02_RawCnts,
    .pTuning = SLD03_E02_Tuning,
};

// Sensor: SLD03, Element: E03
uint16_t SLD03_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning SLD03_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement SLD03_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 1,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = SLD03_E03_RawCnts,
    .pTuning = SLD03_E03_Tuning,
};

// Sensor: WHL00, Element: E00
uint16_t WHL00_E00_RawCnts[CAPT_SELF_FREQ_CNT];
tCaptivateElementTuning WHL00_E00_Tuning[CAPT_SELF_FREQ_CNT];
tElement WHL00_E00 =
{
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 10,
    .pRawCount = WHL00_E00_RawCnts,
    .pTuning = WHL00_E00_Tuning,
};

// Sensor: WHL00, Element: E01
uint16_t WHL00_E01_RawCnts[CAPT_SELF_FREQ_CNT];
tCaptivateElementTuning WHL00_E01_Tuning[CAPT_SELF_FREQ_CNT];
tElement WHL00_E01 =
{
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 10,
    .pRawCount = WHL00_E01_RawCnts,
    .pTuning = WHL00_E01_Tuning,
};

// Sensor: WHL00, Element: E02
uint16_t WHL00_E02_RawCnts[CAPT_SELF_FREQ_CNT];
tCaptivateElementTuning WHL00_E02_Tuning[CAPT_SELF_FREQ_CNT];
tElement WHL00_E02 =
{
    .ui8RxPin = 0,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 10,
    .pRawCount = WHL00_E02_RawCnts,
    .pTuning = WHL00_E02_Tuning,
};

// Sensor: WHL00, Element: E03
uint16_t WHL00_E03_RawCnts[CAPT_SELF_FREQ_CNT];
tCaptivateElementTuning WHL00_E03_Tuning[CAPT_SELF_FREQ_CNT];
tElement WHL00_E03 =
{
    .ui8RxPin = 0,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 10,
    .pRawCount = WHL00_E03_RawCnts,
    .pTuning = WHL00_E03_Tuning,
};


//*****************************************************************************
//
//! Captivate Time Cycle Definitions
//! All time cycles in this application are defined below.  Time cycles are
//! groups of elements that are measured together in parallel in one time slot.
//! Each cycle has 2 components:
//!  1) an element pointer array to the member elements (tElement*)
//!  2) a cycle structure (tCycle)
//
//*****************************************************************************
// Time Cycle: BTN00_C00
tElement* BTN00_C00_Elements[4] =
{
    &BTN00_E00,
    &BTN00_E01,
    &BTN00_E02,
    &BTN00_E03,
};
tCycle BTN00_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = BTN00_C00_Elements,
};

// Time Cycle: BTN00_C01
tElement* BTN00_C01_Elements[4] =
{
    &BTN00_E04,
    &BTN00_E05,
    &BTN00_E06,
    &BTN00_E07,
};
tCycle BTN00_C01 =
{
    .ui8NrOfElements = 4,
    .pElements = BTN00_C01_Elements,
};

// Time Cycle: BTN00_C02
tElement* BTN00_C02_Elements[4] =
{
    &BTN00_E08,
    &BTN00_E09,
    &BTN00_E10,
    &BTN00_E11,
};
tCycle BTN00_C02 =
{
    .ui8NrOfElements = 4,
    .pElements = BTN00_C02_Elements,
};

// Time Cycle: BTN00_C03
tElement* BTN00_C03_Elements[4] =
{
    &BTN00_E12,
    &BTN00_E13,
    &BTN00_E14,
    &BTN00_E15,
};
tCycle BTN00_C03 =
{
    .ui8NrOfElements = 4,
    .pElements = BTN00_C03_Elements,
};

// Time Cycle: SLD00_C00
tElement* SLD00_C00_Elements[4] =
{
    &SLD00_E00,
    &SLD00_E01,
    &SLD00_E02,
    &SLD00_E03,
};
tCycle SLD00_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = SLD00_C00_Elements,
};

// Time Cycle: SLD01_C00
tElement* SLD01_C00_Elements[4] =
{
    &SLD01_E00,
    &SLD01_E01,
    &SLD01_E02,
    &SLD01_E03,
};
tCycle SLD01_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = SLD01_C00_Elements,
};

// Time Cycle: SLD02_C00
tElement* SLD02_C00_Elements[4] =
{
    &SLD02_E00,
    &SLD02_E01,
    &SLD02_E02,
    &SLD02_E03,
};
tCycle SLD02_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = SLD02_C00_Elements,
};

// Time Cycle: SLD03_C00
tElement* SLD03_C00_Elements[4] =
{
    &SLD03_E00,
    &SLD03_E01,
    &SLD03_E02,
    &SLD03_E03,
};
tCycle SLD03_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = SLD03_C00_Elements,
};

// Time Cycle: WHL00_C00
tElement* WHL00_C00_Elements[4] =
{
    &WHL00_E00,
    &WHL00_E01,
    &WHL00_E02,
    &WHL00_E03,
};
tCycle WHL00_C00 =
{
    .ui8NrOfElements = 4,
    .pElements = WHL00_C00_Elements,
};


//*****************************************************************************
//
//! Captivate Sensor Definitions
//! All sensors in this application are defined below.  Sensors are
//! groups of time cycles that utilize raw measurement data to create an
//! abstract sensor type, such as a button, slider, wheel, or prox sensor.
//! Each sensor has 3 components:
//!  1) a cycle pointer array to the member time cycles (tCycle*)
//!  2) a sensor-specific parameter structure (tGenericSensorParams)
//!  3) a sensor structure (tSensor)
//
//*****************************************************************************
//Sensor: BTN00
const tCycle* BTN00_Cycles[4] =
{
    &BTN00_C00,
    &BTN00_C01,
    &BTN00_C02,
    &BTN00_C03,
};

tButtonSensorParams BTN00_Params;
tSensor BTN00 =
{
    // Basic Properties
    .TypeOfSensor = eButtonGroup,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 4,
    .pCycle = BTN00_Cycles,
    .pSensorParams = (tGenericSensorParams*)&BTN00_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = true,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: SLD00
const tCycle* SLD00_Cycles[1] =
{
    &SLD00_C00,
};

tSliderSensorParams SLD00_Params =
{
    .ui8TotalElements = 4,
    .ui16Resolution = 1000,
    .SliderBeta = 100,
    .SliderLower = 0,
    .SliderUpper = 999,
    .SliderAlgorithm = eVectors,
    .SliderFilterEnable = true,
};

tSensor SLD00 =
{
    // Basic Properties
    .TypeOfSensor = eSlider,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 1,
    .pCycle = SLD00_Cycles,
    .pSensorParams = (tGenericSensorParams*)&SLD00_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = false,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: SLD01
const tCycle* SLD01_Cycles[1] =
{
    &SLD01_C00,
};

tSliderSensorParams SLD01_Params =
{
    .ui8TotalElements = 4,
    .ui16Resolution = 1000,
    .SliderBeta = 100,
    .SliderLower = 0,
    .SliderUpper = 999,
    .SliderAlgorithm = eVectors,
    .SliderFilterEnable = true,
};

tSensor SLD01 =
{
    // Basic Properties
    .TypeOfSensor = eSlider,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 1,
    .pCycle = SLD01_Cycles,
    .pSensorParams = (tGenericSensorParams*)&SLD01_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = false,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: SLD02
const tCycle* SLD02_Cycles[1] =
{
    &SLD02_C00,
};

tSliderSensorParams SLD02_Params =
{
    .ui8TotalElements = 4,
    .ui16Resolution = 1000,
    .SliderBeta = 100,
    .SliderLower = 0,
    .SliderUpper = 999,
    .SliderAlgorithm = eVectors,
    .SliderFilterEnable = true,
};

tSensor SLD02 =
{
    // Basic Properties
    .TypeOfSensor = eSlider,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 1,
    .pCycle = SLD02_Cycles,
    .pSensorParams = (tGenericSensorParams*)&SLD02_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = false,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: SLD03
const tCycle* SLD03_Cycles[1] =
{
    &SLD03_C00,
};

tSliderSensorParams SLD03_Params =
{
    .ui8TotalElements = 4,
    .ui16Resolution = 1000,
    .SliderBeta = 100,
    .SliderLower = 0,
    .SliderUpper = 999,
    .SliderAlgorithm = eVectors,
    .SliderFilterEnable = true,
};

tSensor SLD03 =
{
    // Basic Properties
    .TypeOfSensor = eSlider,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 1,
    .pCycle = SLD03_Cycles,
    .pSensorParams = (tGenericSensorParams*)&SLD03_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = false,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: WHL00
const tCycle* WHL00_Cycles[1] =
{
    &WHL00_C00,
};

tWheelSensorParams WHL00_Params =
{
    .ui8TotalElements = 4,
    .ui16Resolution = 1000,
    .SliderBeta = 100,
    .SliderUpper = 1000,
    .SliderLower = 0,
    .SliderAlgorithm = eVectors,
    .SliderFilterEnable = true,
};

tSensor WHL00 =
{
    // Basic Properties
    .TypeOfSensor = eWheel,
    .SensingMethod = eSelf,
    .DirectionOfInterest = eDOIDown,
    .pvCallback = NULL,
    .ui8NrOfCycles = 1,
    .pCycle = WHL00_Cycles,
    .pSensorParams = (tGenericSensorParams*)&WHL00_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 2,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 10,
    .ui16NegativeTouchThreshold = 30,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = false,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};


#if (CAPT_CONDUCTED_NOISE_IMMUNITY_ENABLE==true)
//*****************************************************************************
//
//! \var g_EMCConfig
//! This structure stores the EMC configuration for this application.
//
//*****************************************************************************
const tEMCConfig g_EMCConfig =
{
	// Conversion Style
	.selfModeConversionStyle = CAPT_SELF_MODE_CONVERSION_STYLE,
	.projModeConversionStyle = CAPT_PROJ_MODE_CONVERSION_STYLE,
	
	// Oversampling Style
	.selfModeOversamplingStyle = CAPT_SELF_MODE_OVERSAMPLING_STYLE,
	.projModeOversamplingStyle = CAPT_PROJ_MODE_OVERSAMPLING_STYLE,
	
	// Jitter Filter Enable
	.bJitterFilterEnable = true,
	
	// Noise Thresholds and Calibration Noise Limits
	.ui8NoiseThreshold = CAPT_NOISE_THRESHOLD,
	.ui16CalibrationNoiseLimit = CAPT_CALIBRATION_NOISE_LIMIT,
	.ui8CalibrationTestSampleSize = 8,
		
	// Dynamic Threshold Adjustment Parameters
	.bEnableDynamicThresholdAdjustment = CAPT_DYNAMIC_THRESHOLD_ADJUSTMENT,
	.ui8MaxRelThreshAdj = 76,
	.ui8NoiseLevelFilterEntryThresh = 40,
	.ui8NoiseLevelFilterExitThresh = 0,
	.ui8NoiseLevelFilterDown = 6,
	.ui8NoiseLevelFilterUp = 1,
	.coeffA = _IQ31(0.0065),
	.coeffB = _IQ31(0.050)
};
#endif

//*****************************************************************************
//
//! \var g_pCaptivateSensorArray
//! This array allows for indexed access to any
//! sensor in the configuration.
//
//*****************************************************************************
tSensor* g_pCaptivateSensorArray[CAPT_SENSOR_COUNT] =
{
    &BTN00,
    &SLD00,
    &SLD01,
    &SLD02,
    &SLD03,
    &WHL00,
};


//*****************************************************************************
//
//! \var g_uiApp
//! This structure stores the global settings for this application.
//
//*****************************************************************************
tCaptivateApplication g_uiApp =
{
    .state = eUIActive,
	.pSensorList = &g_pCaptivateSensorArray[0],
    .ui8NrOfSensors = CAPT_SENSOR_COUNT,
    .ui8AppLPM = CAPT_LOW_POWER_MODE,
    .bElementDataTxEnable = true,
    .bSensorDataTxEnable = true,
    .ui16ActiveModeScanPeriod = 33,
    .ui16WakeOnProxModeScanPeriod = 100,
    .ui16InactivityTimeout = 32,
    .ui8WakeupInterval = 5,
};
